/* config.js — generated by the build. Public settings only: the Supabase anon key is designed to be public. */
window.APP_CONFIG = {
  "slug": "branching-story-editor",
  "name": "Story Weaver",
  "supabaseUrl": "",
  "supabaseAnonKey": "",
  "aiProxy": "",
  "google": false,
  "prompts": [
    {
      "say": "Start a sci-fi story about a lighthouse on Mars",
      "does": "Writes the opening and three choices."
    },
    {
      "say": "Only show the secret door if the reader found the key",
      "does": "Adds a condition and an effect to the right choices."
    },
    {
      "say": "Can every ending actually be reached?",
      "does": "Runs the analysis and reports problems."
    }
  ]
};
